baseURL = "https://pure-crystalline.com"
languageCode = "en-us"
title = "Pure Crystalline"
theme = "pure"

#################### default parameters ################################
[params]
# logo = "images/logo.png"
home = "Home"
# Meta data
description = "Pure Crystalline"
author = "Hilde Joosen"
# google map
# gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# mapLatitude = "51.5223477"
# mapLongitude = "-0.1622023"
# mapMarker = "images/marker.png"
# Google Analitycs
# googleAnalitycsID = "Your ID"
# Contact Information
mobile = "+32498201536"
email = "info@pure-crystalline.com"
location = "Oud-turnhout, Begium"
# copyright
copyright = "| @2019 Pure Crystalline |"


############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/gmap.js"

  
############################## navigation ###############################
[menu]
    
#  [[menu.main]]
#  name = "Products"
#  URL = "products"
#  weight = 1
#  
#  [[menu.main]]
#  name = "Blog"
#  URL = "blog"
#  weight = 2
#  
#  [[menu.main]]
#  name = "FAQ"
#  URL = "faq"
#  weight = 3
  
#  [[menu.main]]
#  name = "Contact"
#  URL = "contact"
#  weight = 4
#
  ############## footer menu #############
  #[[menu.footer]]
  #name = "Products"
  #URL = "products"
  #weight = 1
  #
  #[[menu.footer]]
  #name = "Blog"
  #URL = "blog"
  #weight = 2
  #
  #[[menu.footer]]
  #name = "FAQ"
  #URL = "faq"
  #weight = 3
  #
  #[[menu.footer]]
  #name = "Terms & Conditions"
  #URL = "terms-conditions"
  #weight = 4
  #
#  [[menu.footer]]
#  name = "Contact"
#  URL = "contact"
#  weight = 5
#
  # Contact Form
  [params.contact]
  formAction = "https://formspree.io/xpzwklwv"